const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const load = require('./test-load-ts.cjs');
const {receivingWorkItems,workItemSearch,workItemStock,pendingSerialDraft,finishSerialDraft,groupedSerialArrival,handoffCorrectionRequired} = load(path.resolve(__dirname,'receiving-v6.ts'));
const {pendingRows} = load(path.resolve(__dirname,'receiving-v5.ts'));
const empty = () => ({projects:[{id:'A',name:'A案'},{id:'B',name:'B案'}],items:[{id:'i',code:'P401',name:'设备',requires_serial:true,is_active:true},{id:'q',code:'CABLE',requires_serial:false,is_active:true}],materials:[],supplies:[],batches:[],arrivals:[],lines:[],observations:[],matches:[],matchObservations:[],receipts:[],fulfilment:{},scopes:{},scopeErrors:{},transactions:[],closings:[]});
function pending(d,id='p',qty=20,filled=0,item='i',project='A',serials=[]){d.supplies.push({id,receiving_only:true,inventory_item_id:item,project_id:project,quantity:qty,unit:'台'});d.fulfilment['SE_SUPPLY:'+id]={expected:qty,fulfilled:filled,remaining:qty-filled,active:qty>filled,remaining_status:qty>filled?'ACTIVE':'FULFILLED',cancellation:null};serials.forEach((s,i)=>d.observations.push({id:id+i,normalized_serial:s,raw_serial:s,inventory_item_id:item,se_supply_record_id:id,retired_at:null,active_receipt_id:null}));}
function arrival(d,id='a',qty=8,item='q',serials=[]){d.arrivals.push({id,actual_received_at:'2026-09-26T06:20:00Z',project_id:null});d.lines.push({id,arrival_id:id,inventory_item_id:item,quantity:qty,unit:'m',resolution_state:item?'POSTED':'UNRESOLVED',receipt_id:item?id+'r':null});serials.forEach((s,i)=>d.observations.push({id:id+i,arrival_line_id:id,normalized_serial:s,raw_serial:s,inventory_serial_id:id+'s'+i,active_receipt_id:id+'r'}));}
function match(d,line,p,qty,indices=[]){const id=line+p;d.matches.push({id,arrival_line_id:line,se_supply_record_id:p,quantity:qty,cancelled_at:null});indices.forEach(i=>d.matchObservations.push({match_id:id,arrival_entry_id:line+i,cancelled_at:null}));}
const none={result_type:'no_match',candidates:[]};
test('UI-5/6: 20 + 8 + 5 projects into one row, two immutable event identities',()=>{const d=empty();pending(d,'p',20,13,'q');arrival(d,'a',8);arrival(d,'b',5);match(d,'a','p',8);match(d,'b','p',5);const r=receivingWorkItems(d);assert.equal(r.length,1);assert.equal(r[0].received,13);assert.equal(r[0].pending.fulfilment.remaining,7);assert.deepEqual(r[0].slices.map(s=>s.actual.key),['arrival:a','arrival:b']);});
test('UI-17: standalone disappears after full match',()=>{const d=empty();pending(d,'p',20,0,'q');arrival(d);assert.equal(receivingWorkItems(d).length,2);match(d,'a','p',8);d.fulfilment['SE_SUPPLY:p'].fulfilled=8;assert.equal(receivingWorkItems(d).length,1);});
test('UI-18: 10 = matched 6 + unmatched 4, no double count',()=>{const d=empty();pending(d,'p',20,6,'q');arrival(d,'a',10);match(d,'a','p',6);const rows=receivingWorkItems(d);assert.equal(rows.length,2);assert.deepEqual(rows.map(r=>r.slices[0].quantity),[6,4]);assert.equal(rows.flatMap(r=>r.slices).reduce((n,s)=>n+s.quantity,0),10);});
test('serialized partial match partitions exact serials',()=>{const d=empty();pending(d,'p',3,2);arrival(d,'a',3,'i',['X1-AA','X2-AA','X3-AA']);match(d,'a','p',2,[0,2]);const rows=receivingWorkItems(d);assert.deepEqual(rows[0].slices[0].serialIds,['as0','as2']);assert.deepEqual(rows[1].slices[0].serialIds,['as1']);assert(workItemSearch(rows[0],'X3-AA'));assert(!workItemSearch(rows[1],'X3-AA'));});
test('invalid overlapping serial/quantity projection fails closed',()=>{const d=empty();pending(d);pending(d,'b');arrival(d,'a',1,'i',['X1-AA']);match(d,'a','p',1,[0]);match(d,'a','b',1,[0]);assert.throws(()=>receivingWorkItems(d),/不一致/);});
test('legacy receipt groups once, reversal is not an extra work item',()=>{const d=empty();pending(d,'p',2,1);d.receipts.push({id:'old',se_supply_record_id:'p',source_type:'SE_SUPPLY',event_type:'RECEIVE',quantity_received:2,receipt_location:'OFFICE'},{id:'rev',se_supply_record_id:'p',source_type:'SE_SUPPLY',event_type:'REVERSAL',quantity_received:1,reversal_of_id:'old'});const rows=receivingWorkItems(d);assert.equal(rows.length,1);assert.equal(rows[0].slices[0].quantity,1);});
test('UI-7 unique exact preregistration auto-selects pending',()=>{const d=empty();pending(d,'p',20,8,'i','A',['A1234567-AA']);const draft=finishSerialDraft(pendingSerialDraft('a1234567-aa',d),none,d);assert.equal(draft.pendingKey,'SE_SUPPLY:p');assert.equal(draft.choiceRequired,false);});
test('multiple pending aliases never select first',()=>{const d=empty();pending(d,'a',20,0,'i','A',['7515CA50-A4']);pending(d,'b',20,0,'i','B',['7515CA50-A4']);const draft=pendingSerialDraft('7515CA50-A4',d);assert.equal(draft.pendingKey,null);assert.equal(draft.candidates.length,2);assert(draft.choiceRequired);assert.throws(()=>groupedSerialArrival([draft],pendingRows(d)),/請先選擇/);});
test('explicit project conflict prevents auto-match',()=>{const d=empty();pending(d,'a',20,0,'i','A',['7515CA50-A4']);const draft=pendingSerialDraft('7515CA50-A4',d,'B');assert.equal(draft.pendingKey,null);});
test('already claimed preregistration is not reused',()=>{const d=empty();pending(d,'a',20,0,'i','A',['7515CA50-A4']);d.matchObservations.push({pending_entry_id:'a0',cancelled_at:null});assert.equal(pendingSerialDraft('7515CA50-A4',d).pendingKey,null);});
test('canonical existing identity prevents a second IN, regardless of pending hit',()=>{const d=empty();pending(d,'a',20,0,'i','A',['7515CA50-A4']);const r=finishSerialDraft(pendingSerialDraft('7515CA50-A4',d),{result_type:'unique_match',candidates:[{id:'existing'}]},d);assert.equal(r.state,'conflict');assert.equal(r.itemId,null);assert.equal(r.pendingKey,null);});
test('UI-8 batch groups 12 / 5 / 3 without per-serial assignment',()=>{const d=empty();const a=Array.from({length:12},(_,i)=>'P401A'+i+'-AA'),b=Array.from({length:5},(_,i)=>'P401B'+i+'-AA');pending(d,'a',20,0,'i','A',a);pending(d,'b',20,0,'i','B',b);const drafts=[...a,...b,'UNKNOWN1-AA','UNKNOWN2-AA','UNKNOWN3-AA'].map(s=>finishSerialDraft(pendingSerialDraft(s,d),none,d));const g=groupedSerialArrival(drafts,pendingRows(d));assert.deepEqual(g.matches.map(m=>m.quantity),[12,5]);assert.equal(g.lines.reduce((n,l)=>n+l.quantity,0),20);assert.equal(g.lines.filter(l=>!l.inventory_item_id).length,3);});
test('UI-9/10 no safe identity remains independently completable unknown arrival',()=>{const d=empty();const v=finishSerialDraft(pendingSerialDraft('UNKNOWN1-AA',d),none,d);assert.equal(v.itemId,null);assert.equal(v.pendingKey,null);arrival(d,'u',1,null,['UNKNOWN1-AA']);assert.equal(receivingWorkItems(d)[0].status,'待補資料');});
test('same item alone never automatically links unrelated pending',()=>{const d=empty();pending(d);const v=finishSerialDraft(pendingSerialDraft('UNLISTED-AA',d),none,d,pendingRows(d)[0]);assert.equal(v.itemId,'i');assert.equal(v.pendingKey,null);});
test('group submission refuses stale capacity',()=>{const d=empty();pending(d,'p',1,0,'i','A',['S0000001-AA','S0000002-AA']);const ds=d.observations.map(e=>pendingSerialDraft(e.raw_serial,d));assert.throws(()=>groupedSerialArrival(ds,pendingRows(d)),/超過/);});
test('stock badges follow exact serial allocation state; retract restores availability',()=>{const d=empty();arrival(d,'a',2,'i',['A1-AA','A2-AA']);d.scopes.ar={received:2,requires_serial:true,available:1,se:1,site:0,available_serial_ids:['as1'],allocations:[{inventory_serial_id:'as0',quantity:1,route_type:'SE',cancelled_at:null}]};const row=receivingWorkItems(d)[0];assert.equal(workItemStock(row,d).se,1);d.scopes.ar.allocations[0].cancelled_at='now';d.scopes.ar.available_serial_ids.push('as0');assert.equal(workItemStock(row,d).available,2);});
test('nonserial partial receipt never invents allocation-to-pending provenance',()=>{const d=empty();pending(d,'p',20,6,'q');arrival(d,'a',10);match(d,'a','p',6);d.scopes.ar={received:10,requires_serial:false,available:5,se:5,site:0};for(const row of receivingWorkItems(d)){const s=workItemStock(row,d);assert(s.shared);assert.equal(s.se,0);assert.equal(s.available,0);}});
test('UI-16 terminal and closed original/current month hide ordinary retract',()=>{const d=empty(),a={state:'ACTIVE',route_type:'SITE',inventory_transaction_id:'t',site_receipt_id:'r'},scope={allocations:[a]};d.transactions.push({id:'t',transaction_type:'OUT',quantity:1,transaction_date:'2026-09-26'});d.receipts.push({id:'r',quantity_received:1});assert.equal(handoffCorrectionRequired(a,scope,d,new Date('2026-10-01T00:00:00Z')),false);d.closings.push({year:'2026',month:'10',status:'CLOSED'});assert.equal(handoffCorrectionRequired(a,scope,d,new Date('2026-10-01T00:00:00Z')),true);d.closings=[];a.state='USED';assert.equal(handoffCorrectionRequired(a,scope,d),true);});
