const assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path'),fs=require('node:fs');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const load=(file,mocks={})=>require('./test-load-ts.cjs')(path.join(__dirname,file),mocks);
const read=file=>fs.readFileSync(path.join(__dirname,file),'utf8');
const {resolveDashboardViews:resolve}=load('dashboard-perspectives.ts');
const {getCurrentAndNextNodeBatches:batches,getCurrentAndNextMilestones,getVisibleWorkflowMilestones,getProjectOuterWorkflowFields}=load('project-workflow.ts');
const {presentBusinessDate:date}=load('date-presentation.ts');
const {selectScheduleTasksByWorkGroup:select}=load('schedule-selectors.ts');
const {sortWorkItems,workItemTimeline}=load('workbench.ts');
const views=['ENGINEERING','PROJECT_MANAGEMENT','DESIGN'].map((key,i)=>({id:key,key,name:key,is_active:true,sort_order:i}));
const member={id:'m',role:'ENGINEER',category:'OTHER'};
const link=(key,is_default=false)=>({member_id:'m',dashboard_view_id:key,is_default});
test('no perspective rows => read-only engineering fallback',()=>{const rows=[];assert.equal(resolve(member,views,rows).defaultView.key,'ENGINEERING');assert.deepEqual(rows,[]);});
test('ADMIN sees all active perspectives without membership',()=>assert.equal(resolve({...member,role:'ADMIN'},views,[]).allowed.length,3));
test('ADMIN assignment does not restrict all-view access',()=>assert.equal(resolve({...member,role:'ADMIN'},views,[link('DESIGN',true)]).allowed.length,3));
test('ADMIN explicitly assigned default wins',()=>assert.equal(resolve({...member,role:'ADMIN'},views,[link('DESIGN',true)]).defaultView.key,'DESIGN'));
test('non-admin sees only assigned active views',()=>assert.deepEqual(resolve(member,views,[link('DESIGN')]).allowed.map(v=>v.key),['DESIGN']));
test('existing disabled membership does not grant legacy engineering',()=>assert.equal(resolve(member,views.map(v=>({...v,is_active:v.key!=='DESIGN'})),[link('DESIGN')]).allowed.length,0));
test('other member memberships do not affect own fallback',()=>assert.equal(resolve(member,views,[{...link('DESIGN'),member_id:'other'}]).defaultView.key,'ENGINEERING'));
test('positions/category cannot choose perspective',()=>assert.equal(resolve({...member,category:'PROJECT',position:'電力設計'},views,[]).defaultView.key,'ENGINEERING'));
test('resolver leaves role position groups and memberships unchanged',()=>{const m={...member,positions:['p'],work_groups:['g']},rows=[link('DESIGN')],before=JSON.stringify([m,rows,views]);resolve(m,views,rows);assert.equal(JSON.stringify([m,rows,views]),before);});
test('sidebar system management remains role-gated separately from selector',()=>{const src=read('../components/SidebarV3.tsx');assert.match(src,/currentRole === 'admin' &&/);assert.match(src,/<DashboardViewSelector/);assert.doesNotMatch(src,/selected\.key.*系統管理/);});
test('view selection has no persistence mutation',()=>{const src=read('../components/DashboardViewContext.tsx');assert.match(src,/const select=.*setState/);assert.doesNotMatch(src,/\.update\(|\.insert\(|\.rpc\(|setMemberDashboardViews/);});
const node=(id,sort_order,status='NOT_STARTED',extra={})=>({id,sort_order,status,created_at:'2026-01-01',deleted_at:null,is_applicable:true,project_id:'p',phase_key_snapshot:'ANY',phase_name_snapshot:'任意階段',label:id,...extra});
const ids=rows=>rows.map(row=>row.id);
test('all IN_PROGRESS and BLOCKED are current, across orders',()=>assert.deepEqual(ids(batches([node('a',1,'IN_PROGRESS'),node('b',3,'BLOCKED'),node('c',4)]).current_nodes),['a','b']));
test('fallback keeps whole min incomplete batch',()=>assert.deepEqual(ids(batches([node('a',1,'COMPLETED'),node('b',2),node('c',2),node('d',3)]).current_nodes),['b','c']));
test('next starts after maximum active current order',()=>assert.deepEqual(ids(batches([node('a',1,'IN_PROGRESS'),node('skip',2),node('b',3,'BLOCKED'),node('c',4),node('d',4)]).next_nodes),['c','d']));
test('next excludes completed nonapplicable deleted archived',()=>assert.deepEqual(ids(batches([node('a',1),node('done',2,'COMPLETED'),node('off',2,'NOT_STARTED',{is_applicable:false}),node('deleted',2,'NOT_STARTED',{deleted_at:'x'}),node('archive',2,'NOT_STARTED',{archived_at:'x'}),node('b',3)]).next_nodes),['b']));
test('completed workflow has no current/next',()=>assert.deepEqual(batches([node('a',1,'COMPLETED')]),{current_nodes:[],next_nodes:[]}));
test('parallel node arrays preserve source and deterministic ties',()=>{const data=[node('b',1),node('a',1)];assert.deepEqual(ids(batches(data).current_nodes),['a','b']);assert.deepEqual(ids(data),['b','a']);});
test('archived nodes excluded from old summary and main workflow',()=>{const data=[node('a',1,'IN_PROGRESS',{archived_at:'x'}),node('b',2)];assert.equal(getCurrentAndNextMilestones(data).current.id,'b');assert.deepEqual(ids(getVisibleWorkflowMilestones(data,false)),['b']);});
test('archived meter no longer provides outer active date',()=>assert.equal(getProjectOuterWorkflowFields([node('a',1,'NOT_STARTED',{milestone_key:'METER_INSTALLATION',planned_date:'2026-01-01',archived_at:'x'})],null).meter_expected_date,null));
test('project overview renders arbitrary phase and +N without name matching',()=>{const {ProjectOverviewCards}=load('../components/ProjectOverviewCards.tsx');const markup=renderToStaticMarkup(React.createElement(ProjectOverviewCards,{projects:[{id:'p',name:'案件'}],milestones:[1,2,3,4].map(i=>node('m'+i,1,'IN_PROGRESS')),onOpen:()=>{}}));assert.match(markup,/任意階段/);assert.match(markup,/\+1/);assert.equal((markup.match(/<button /g)||[]).length,1);});
test('project card opens existing project and first current node',()=>{const {ProjectOverviewCards}=load('../components/ProjectOverviewCards.tsx');let selection;const tree=ProjectOverviewCards({projects:[{id:'p',name:'案'}],milestones:[node('n',1)],onOpen:(...v)=>selection=v});tree.props.children[0].props.onClick();assert.equal(selection[0].id,'p');assert.equal(selection[1],'n');});
test('project TEAM source uses PROJECT while My TODO remains global',()=>{const src=read('../app/page.tsx');assert.match(src,/todoGroupKey=projectManagement\?'PROJECT':'ENGINEERING'/);assert.match(src,/getPrivateTodos\(\)/);assert.match(src,/selectTodayMemberSchedule/);});
const scheduleGroups=[{id:'E',key:'ENGINEERING',is_active:true,sort_order:10},{id:'P',key:'PROJECT',is_active:true,sort_order:20}];
const context={users:[{id:'e',category:'ENGINEERING'},{id:'p',category:'OTHER'},{id:'other',category:'OTHER'}],members:[{task_id:'project',user_id:'e'}],memberships:[{member_id:'p',work_group_id:'P'}],groups:scheduleGroups};
const tasks=[{id:'engineering',work_group_id:'E',main_assignee_id:'p'},{id:'project',work_group_id:'P',main_assignee_id:'other'}];
test('PROJECT owner plus engineering assistant appears in engineering',()=>assert.deepEqual(ids(select(tasks,'E',context)),['engineering','project']));
test('ENGINEERING owner plus project primary appears in project',()=>assert.deepEqual(ids(select(tasks,'P',context)),['engineering','project']));
test('same task id deduplicated and owner never altered',()=>{const clone=JSON.stringify(tasks);assert.equal(select([...tasks,tasks[1]],'E',context).length,2);assert.equal(JSON.stringify(tasks),clone);assert.equal(select(tasks,'E',context)[1].work_group_id,'P');});
test('explicit membership overrides legacy engineering category',()=>assert.deepEqual(ids(select(tasks,'E',{...context,memberships:[...context.memberships,{member_id:'e',work_group_id:'P'}]})),['engineering']));
test('OTHER and MANAGEMENT do not imply PROJECT membership',()=>assert.deepEqual(ids(select(tasks,'P',{...context,memberships:[]})),['project']));
test('participant zero membership plus ENGINEERING category uses legacy ENGINEERING',()=>assert.deepEqual(ids(select(tasks,'E',context)),['engineering','project']));
test('participant inactive-only membership never falls back to ENGINEERING',()=>{
 const groups=scheduleGroups.map(group=>({...group,is_active:group.id!=='P'}));
 const memberships=[...context.memberships,{member_id:'e',work_group_id:'P'}];
 assert.deepEqual(ids(select(tasks,'E',{...context,groups,memberships})),['engineering']);
});
test('visibility never calls Google or changes eligibility',()=>{const src=read('schedule-selectors.ts');assert.doesNotMatch(src,/syncToGoogle|google_calendar_sync_enabled|fetch\(/);});
for(const [planned,label] of [['2026-09-12','預計 2026/09/12'],['2026-09-11','預計 2026/09/11'],['2026-09-10','預計 2026/09/10 · 逾期']])test('date incomplete '+planned,()=>{const p=date({planned,today:'2026-09-11'});assert.equal(p.label,label);assert.notEqual(p.kind,'actual');});
test('actual field is explicit actual even after today',()=>assert.equal(date({planned:'2026-01-01',actual:'2026-09-12',today:'2026-09-11'}).label,'實際 2026/09/12'));
test('completed without actual preserves original planned attribution',()=>assert.equal(date({planned:'2026-01-01',completed:true,today:'2026-09-11'}).label,'已完成 · 原預計 2026/01/01'));
test('completed without either date has no invented actual',()=>assert.equal(date({completed:true,today:'2026-09-11'}).label,'已完成'));
const item=(id,due_date,extra={})=>({id,due_date,status:'待處理',received_at:'2026-09-01T01:00:00Z',work_zone_id:'a',...extra});
test('work item order overdue today upcoming no-date completed',()=>assert.deepEqual(ids(sortWorkItems([item('none',null),item('future','2026-09-12'),item('today','2026-09-11'),item('past','2026-09-10'),item('done','2026-01-01',{status:'已完成'})],'2026-09-11')),['past','today','future','none','done']));
test('timeline exposes all four day-level fields without inferred completion',()=>{const points=workItemTimeline(item('i','2026-09-12',{expected_start_date:'2026-09-10',completed_at:'2026-09-13T00:00:00Z'}));assert.equal(points.length,4);assert.equal(points[3].date,'2026-09-13');assert.equal(workItemTimeline(item('i','2026-09-01')).length,2);});
test('Design projects use assignment ids not legacy names',()=>{const src=read('db/workbench-adapter.ts');assert.match(src,/from\('project_position_assignments'\).*eq\('member_id',memberId\)/);assert.doesNotMatch(src,/responsible_member_name/);});
test('promotion reuses Foundation RPC and does not copy Todo',()=>{const src=read('db/workbench-adapter.ts');assert.match(src,/rpc\('promote_private_todo_to_work_item'/);assert.doesNotMatch(src,/from\('work_items'\)\.insert/);});
test('workbench layout has scoped scrolling and no blank third zone',()=>{const src=read('../components/DesignWorkbench.tsx');assert.match(src,/zones\.map\(zone/);assert.match(src,/md:min-w-\[190px\]/);assert.match(src,/min-w-0 overflow-x-auto/);assert.match(src,/min-\[1100px\]:grid-cols-/);});
test('mobile perspectives expose touch tabs and inline Todo text',()=>{const src=read('../components/DesignWorkbench.tsx');assert.match(src,/\['projects','專案'\],\['work','工作'\],\['todos','TODO'\]/);assert.match(src,/<TodoInlineText/);assert.match(src,/aria-label="工作區"/);});
test('inline editor has no mandatory modal and uses shared mutation',()=>{const src=read('../components/TodoInlineText.tsx');assert.match(src,/saveTodoText\(dbAdapter/);assert.match(src,/onClick=\{open\}/);assert.match(src,/nativeEvent.isComposing/);assert.match(src,/e.key==='Escape'/);assert.match(src,/e.ctrlKey\|\|e.metaKey/);assert.doesNotMatch(src,/role="dialog"|onContextMenu|hover-only/);});
test('rebuild requires preview token and offers archive history',()=>{assert.match(read('../components/WorkflowRebuild.tsx'),/p_preview_token:preview.token/);const src=read('../components/ProjectWorkflow.tsx');assert.match(src,/封存流程歷史/);assert.match(src,/同步模板新增項目/);assert.doesNotMatch(src,/重製流程/);assert.match(src,/milestone.phase_name_snapshot/);assert.match(src,/phase_key_snapshot === 'CONSTRUCTION'/);});

function inlineHarness(scope='PRIVATE') {
 let cursor=0;const state=[],writes=[];
 const hooks={...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=initial;return [state[i],next=>{state[i]=typeof next==='function'?next(state[i]):next;}];},useRef(initial){const i=cursor++;if(!(i in state))state[i]={current:initial};return state[i];}};
 const adapter={updatePrivateTodo:async(id,data)=>writes.push({scope:'PRIVATE',id,data}),updateTodo:async(id,data)=>writes.push({scope:'TEAM',id,data})};
 const {TodoInlineText}=load('../components/TodoInlineText.tsx',{'react':hooks,'./UserContext':{useUser:()=>({currentUser:{id:'m',role:'ENGINEER',is_active:true}})},'@/lib/db':{dbAdapter:adapter}});
 const render=()=>{cursor=0;return TodoInlineText({todo:{id:'t',title:'original',content:'body',created_by:'m',scope,status:'待安排'},onSaved:async()=>{}});};
 const walk=(el,predicate)=>{if(!el||typeof el!=='object')return null;if(predicate(el))return el;for(const child of React.Children.toArray(el.props?.children)){const found=walk(child,predicate);if(found)return found;}return null;};
 const find=type=>walk(render(),el=>el.type===type);
 find('button').props.onClick();
 return {render,find,writes};
}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
for(const scope of ['PRIVATE','TEAM'])test(scope+' direct text Enter saves only title/content via shared mutation',async()=>{const h=inlineHarness(scope);h.find('input').props.onChange({target:{value:'changed'}});h.find('input').props.onKeyDown({key:'Enter',nativeEvent:{isComposing:false},preventDefault(){}});await flush();assert.deepEqual(h.writes,[{scope,id:'t',data:{title:'changed',content:'body'}}]);});
test('inline Escape cancels without blur mutation',async()=>{const h=inlineHarness();h.find('input').props.onChange({target:{value:'discard'}});const tree=h.render();tree.props.onKeyDown({key:'Escape',preventDefault(){}});tree.props.onBlur({currentTarget:{contains:()=>false},relatedTarget:null});await flush();assert.equal(h.writes.length,0);});
test('inline IME Enter never saves prematurely',async()=>{const h=inlineHarness();h.find('input').props.onKeyDown({key:'Enter',nativeEvent:{isComposing:true},preventDefault(){}});await flush();assert.equal(h.writes.length,0);});
test('inline blank title retains editor and blocks write',async()=>{const h=inlineHarness();h.find('input').props.onChange({target:{value:'  '}});h.render().props.onBlur({currentTarget:{contains:()=>false},relatedTarget:null});await flush();assert.equal(h.writes.length,0);assert.ok(h.find('input'));});
test('inline internal focus does not save, external blur saves once',async()=>{const h=inlineHarness();h.render().props.onBlur({currentTarget:{contains:()=>true},relatedTarget:{}});assert.equal(h.writes.length,0);const tree=h.render();tree.props.onBlur({currentTarget:{contains:()=>false},relatedTarget:null});tree.props.onBlur({currentTarget:{contains:()=>false},relatedTarget:null});await flush();assert.equal(h.writes.length,1);});
test('multiline Enter preserves newline while Ctrl+Enter saves',async()=>{const h=inlineHarness();h.find('textarea').props.onChange({target:{value:'line1\nline2'}});h.find('textarea').props.onKeyDown({key:'Enter',nativeEvent:{isComposing:false},ctrlKey:false,preventDefault(){}});assert.equal(h.writes.length,0);h.find('textarea').props.onKeyDown({key:'Enter',nativeEvent:{isComposing:false},ctrlKey:true,preventDefault(){}});await flush();assert.equal(h.writes[0].data.content,'line1\nline2');});
for(const count of [0,2,3])test('Design SSR '+count+' zone configuration renders actual zone names only',()=>{
 const zones=Array.from({length:count},(_,i)=>({id:'z'+i,name:'Fixture zone '+i,is_active:true,sort_order:i}));let call=0;
 const seeds={0:zones,1:[],2:[],3:[],4:[],5:[],6:'',7:false,8:'work',9:'z0'};
 const hooks={...React,useState(initial){const i=call++;return [i in seeds?seeds[i]:initial,()=>{}];}};
 const {DesignWorkbench}=load('../components/DesignWorkbench.tsx',{'react':hooks,'./UserContext':{useUser:()=>({currentUser:{id:'m',role:'ENGINEER'}})},'@/lib/db':{dbAdapter:{}},'@/lib/db/workbench-adapter':{workbenchAdapter:{}},'./ProjectDetailModal':{ProjectDetailModal:()=>null}});
 const markup=renderToStaticMarkup(React.createElement(DesignWorkbench));
 if(count===0)assert.match(markup,/先建立 2 或 3 個工作區/);else for(let i=0;i<count;i++)assert.match(markup,new RegExp('Fixture zone '+i));
 assert.doesNotMatch(markup,new RegExp('Fixture zone '+count));
});
