// In Phase 1, Supabase adapter is a stub to ensure compatibility
export const supabaseDbAdapter = {
  getUsers: async () => { throw new Error('Supabase not configured yet'); },
  createUser: async (u: any) => { throw new Error('Supabase not configured yet'); },
  updateUser: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  getProjects: async () => { throw new Error('Supabase not configured yet'); },
  createProject: async (p: any) => { throw new Error('Supabase not configured yet'); },
  updateProject: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  getActiveProjects: async () => { throw new Error('Supabase not configured yet'); },
  updateActiveProject: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  getTodos: async () => { throw new Error('Supabase not configured yet'); },
  createTodo: async (t: any) => { throw new Error('Supabase not configured yet'); },
  updateTodo: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  deleteTodo: async (id: string) => { throw new Error('Supabase not configured yet'); },
  getScheduleTasks: async () => { throw new Error('Supabase not configured yet'); },
  createScheduleTask: async (t: any, m: any) => { throw new Error('Supabase not configured yet'); },
  updateScheduleTask: async (id: string, updates: any, m?: any) => { throw new Error('Supabase not configured yet'); },
  deleteScheduleTask: async (id: string) => { throw new Error('Supabase not configured yet'); },
  getScheduleTaskMembers: async () => { throw new Error('Supabase not configured yet'); },
  getInventoryItems: async () => { throw new Error('Supabase not configured yet'); },
  createInventoryItem: async (t: any) => { throw new Error('Supabase not configured yet'); },
  updateInventoryItem: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  deleteInventoryItem: async (id: string) => { throw new Error('Supabase not configured yet'); },
  getInventoryTransactions: async () => { throw new Error('Supabase not configured yet'); },
  getInventoryBatches: async () => { throw new Error('Supabase not configured yet'); },
  createInventoryTransaction: async (t: any, serialsData: any = [], user: string = 'system') => { throw new Error('Supabase not configured yet'); },
  updateInventoryTransaction: async (id: string, updates: any, serialsData: any = [], reason: string, user: string) => { throw new Error('Supabase not configured yet'); },
  voidInventoryTransaction: async (id: string, reason: string, user: string) => { throw new Error('Supabase not configured yet'); },
  getInventorySerials: async () => { throw new Error('Supabase not configured yet'); },
  createInventorySerial: async (t: any) => { throw new Error('Supabase not configured yet'); },
  updateInventorySerial: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  deleteInventorySerial: async (id: string) => { throw new Error('Supabase not configured yet'); },
  getInventoryTransactionSerials: async () => { throw new Error('Supabase not configured yet'); },
  updateInventoryTransactionSerial: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  getInventoryBalances: async () => { throw new Error('Supabase not configured yet'); },
  getActivityLogs: async () => { throw new Error('Supabase not configured yet'); },
  logActivity: async (log: any) => { throw new Error('Supabase not configured yet'); },
  getMonthlyClosings: async () => { throw new Error('Supabase not configured yet'); },
  getMonthlyClosingItems: async (closingId: string) => { throw new Error('Supabase not configured yet'); },
  createMonthlyClosing: async (closing: any, items: any) => { throw new Error('Supabase not configured yet'); },
  getSESupplyRecords: async () => { throw new Error('Supabase not configured yet'); },
  createSESupplyRecord: async (data: any) => { throw new Error('Supabase not configured yet'); },
  updateSESupplyRecord: async (id: string, updates: any) => { throw new Error('Supabase not configured yet'); },
  deleteSESupplyRecord: async (id: string) => { throw new Error('Supabase not configured yet'); },
};
