'use client';
import {useCallback,useEffect,useState} from 'react';
import {format} from 'date-fns';
import {useUser} from './UserContext';
import {dbAdapter} from '@/lib/db';
import {workbenchAdapter} from '@/lib/db/workbench-adapter';
import {sortWorkItems,workItemTimeline,type WorkItem,type WorkZone} from '@/lib/workbench';
import type {Project,ProjectMilestone,Todo} from '@/lib/db/types';
import {TodoInlineText} from './TodoInlineText';
import {ProjectOverviewCards} from './ProjectOverviewCards';
import {ProjectDetailModal} from './ProjectDetailModal';
import {selectActiveProjects} from '@/lib/project-selectors';
import {selectActiveTeamTodos} from '@/lib/todo-selectors';
const field='min-h-11 w-full min-w-0 rounded border border-theme-border bg-page p-2';
export function DesignWorkbench() {
 const {currentUser}=useUser();
 const [zones,setZones]=useState<WorkZone[]>([]),[items,setItems]=useState<WorkItem[]>([]),[projects,setProjects]=useState<Project[]>([]),[myIds,setMyIds]=useState<string[]>([]),[milestones,setMilestones]=useState<ProjectMilestone[]>([]),[todos,setTodos]=useState<Todo[]>([]),[teamTodos,setTeamTodos]=useState<Todo[]>([]);
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('projects'),[workTab,setWorkTab]=useState(''),[timeline,setTimeline]=useState(false),[configure,setConfigure]=useState(false),[title,setTitle]=useState(''),[receivedDate,setReceivedDate]=useState(format(new Date(),'yyyy-MM-dd')),[saving,setSaving]=useState(false),[promote,setPromote]=useState<Todo|null>(null),[editing,setEditing]=useState<WorkItem|null>(null),[selected,setSelected]=useState<{project:Project;milestoneId:string|null}|null>(null);
 const today=format(new Date(),'yyyy-MM-dd');const editable=!!currentUser&&currentUser.role!=='VIEWER';
 const load=useCallback(async()=>{if(!currentUser)return;try{const [z,i,p,ids,t,groups]=await Promise.all([workbenchAdapter.getZones(currentUser.id),workbenchAdapter.getItems(currentUser.id),dbAdapter.getProjects(),workbenchAdapter.getAssignedProjectIds(currentUser.id),dbAdapter.getPrivateTodos(),dbAdapter.getWorkGroups()]);const projectGroup=groups.find(group=>group.is_active&&group.key==='PROJECT');const [m,team]=await Promise.all([workbenchAdapter.getMilestones(ids),projectGroup?dbAdapter.getTodos(projectGroup.id):Promise.resolve([])]);setZones(z);setItems(i);setProjects(p);setMyIds(ids);setMilestones(m);setTodos(t);setTeamTodos(team);setWorkTab(old=>z.some(v=>v.id===old)?old:z[0]?.id||'');setError('');}catch{setError('無法載入設計工作台，請確認測試環境資料與 candidate migration。');}finally{setLoading(false);}},[currentUser]);
 useEffect(()=>{void load();},[load]);
 const ordered=sortWorkItems(items,today);const myProjects=selectActiveProjects(projects).filter(p=>myIds.includes(p.id));const activeTeamTodos=selectActiveTeamTodos(teamTodos);
 if(loading)return <p className="p-5">載入設計工作台…</p>;
 return <div className="min-w-0 space-y-4 p-4 text-primary md:p-6 min-[1100px]:h-[100dvh] min-[1100px]:overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-2"><h1 className="text-2xl font-bold">設計工作台</h1><button disabled={!editable} className="min-h-11 rounded border px-3" onClick={()=>setConfigure(true)}>設定工作區</button></header>{error&&<p role="alert" className="text-danger">{error}</p>}
 <nav aria-label="設計視角頁面" className="grid grid-cols-3 gap-1 md:hidden">{[['projects','專案'],['work','工作'],['todos','TODO']].map(([key,label])=><button key={key} type="button" aria-pressed={tab===key} className="min-h-11 rounded border border-theme-border aria-pressed:bg-accent/20" onClick={()=>setTab(key)}>{label}</button>)}</nav>
 <div className="grid min-w-0 items-start gap-4 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)] min-[1100px]:h-[calc(100%-4rem)] min-[1100px]:min-h-0 min-[1100px]:grid-cols-[minmax(0,.9fr)_minmax(0,2.4fr)_minmax(0,.9fr)] min-[1100px]:items-stretch min-[1100px]:[&>section]:h-full min-[1100px]:[&>section]:overflow-y-auto">
 <section className={`${tab==='projects'?'block':'hidden'} min-w-0 md:block`}><h2 className="mb-3 font-semibold">我的專案</h2><ProjectOverviewCards projects={myProjects} milestones={milestones} pending={id=>items.filter(i=>i.project_id===id&&i.status!=='已完成').length} onOpen={(project,milestoneId)=>setSelected({project,milestoneId})}/></section>
 <section className={`${tab==='work'?'block':'hidden'} min-w-0 md:block`}><div className="mb-3 hidden gap-2 md:flex"><button className="min-h-11 rounded border px-3" aria-pressed={!timeline} onClick={()=>setTimeline(false)}>工作區</button><button className="min-h-11 rounded border px-3" aria-pressed={timeline} onClick={()=>setTimeline(true)}>時間軸</button></div>
 {!zones.length?<div className="rounded border border-dashed p-5"><p>先建立 2 或 3 個工作區，自訂名稱。</p><button disabled={!editable} onClick={()=>setConfigure(true)} className="mt-3 min-h-11 rounded border px-3">開始設定</button></div>:<><nav aria-label="工作區" className="mb-3 flex min-w-0 flex-wrap gap-1 md:hidden">{zones.map(zone=><button className="min-h-11 max-w-full break-words rounded border px-3" key={zone.id} aria-pressed={!timeline&&workTab===zone.id} onClick={()=>{setWorkTab(zone.id);setTimeline(false);}}>{zone.name}</button>)}<button className="min-h-11 rounded border px-3" aria-pressed={timeline} onClick={()=>setTimeline(true)}>時間軸</button></nav>
 {timeline?<div className="space-y-3" aria-label="日粒度工作時間軸">{ordered.map(item=><article key={item.id} className="rounded border border-theme-border p-3"><button className="min-h-11 break-words text-left font-semibold" onClick={()=>setEditing(item)}>{item.title}</button><ol className="flex flex-wrap gap-3 text-xs">{workItemTimeline(item).map(point=><li key={point.label}><span className="block text-secondary">{point.label}</span>{point.date}</li>)}</ol>{item.status!=='已完成'&&item.due_date&&item.due_date<today&&<p className="text-danger">逾期</p>}</article>)}</div>:<div className="min-w-0 overflow-x-auto"><div className="flex gap-3">{zones.map(zone=><section key={zone.id} className={`${workTab===zone.id?'block':'hidden'} w-full min-w-0 flex-1 md:block md:min-w-[190px]`}><h2 className="mb-3 break-words font-bold">{zone.name}</h2><div className="space-y-3">{ordered.filter(i=>i.work_zone_id===zone.id).map(item=><button type="button" key={item.id} onClick={()=>setEditing(item)} className="w-full min-w-0 rounded-xl border border-theme-border bg-card p-3 text-left"><p className="break-words text-xs text-secondary">{projects.find(p=>p.id===item.project_id)?.name||'未指定案件'}</p><h3 className="my-2 break-words font-semibold">{item.title}</h3><dl className="space-y-1 text-xs"><div>收到：{item.received_at.slice(0,10)}</div>{item.expected_start_date&&<div>預計開始：{item.expected_start_date}</div>}<div>預計完成：{item.due_date||'未設定'}</div><div>{item.status}{item.status!=='已完成'&&item.due_date&&item.due_date<today&&<span className="text-danger"> · 逾期</span>}</div></dl></button>)}{!items.some(i=>i.work_zone_id===zone.id)&&<p className="text-sm text-secondary">尚無工作項目，可由 TODO 移入。</p>}</div></section>)}</div></div>}</>}
 </section>
 <section className={`${tab==='todos'?'block':'hidden'} min-w-0 space-y-5 md:col-span-2 md:block min-[1100px]:col-span-1`}><div><h2 className="mb-3 font-semibold">我的 TODO</h2><form onSubmit={async e=>{e.preventDefault();if(!title.trim()||!currentUser||saving)return;setSaving(true);try{await dbAdapter.createPrivateTodo({title:title.trim(),created_by:currentUser.id,received_at:receivedDate+'T00:00:00+08:00'});setTitle('');setReceivedDate(format(new Date(),'yyyy-MM-dd'));await load();}catch{setError('新增待辦失敗');}finally{setSaving(false);}}} className="mb-3 space-y-2"><input aria-label="新增私人記事" placeholder="先記下來…" className={field} value={title} disabled={!editable||saving} onChange={e=>setTitle(e.target.value)}/><label className="block text-xs text-secondary">收到日期<input aria-label="收到日期" required type="date" className={field} value={receivedDate} disabled={!editable||saving} onChange={e=>setReceivedDate(e.target.value)}/></label><button disabled={!editable||saving||!title.trim()} className="min-h-11">新增</button></form><div className="space-y-3">{todos.filter(t=>t.status!=='已完成').map(todo=><article key={todo.id} className="min-w-0 rounded border border-theme-border p-3"><TodoInlineText todo={todo} onSaved={load}/><p className="text-xs text-secondary">{(todo.received_at||todo.created_at).slice(5,10).replace('-','/')} 收到</p>{todo.status==='待安排'&&<div className="flex flex-wrap gap-2"><button disabled={!editable||!zones.length} onClick={()=>setPromote(todo)} className="min-h-11 text-sm text-accent">移入工作區 ▾</button><button disabled={!editable||saving} className="min-h-11 text-sm" onClick={async()=>{setSaving(true);try{await dbAdapter.updatePrivateTodo(todo.id,{status:'已完成'});await load();}catch{setError('待辦更新失敗');}finally{setSaving(false);}}}>完成</button></div>}</article>)}</div></div><div><h2 className="mb-3 font-semibold">團隊 TODO</h2><div className="space-y-3">{activeTeamTodos.map(todo=><article key={todo.id} className="min-w-0 rounded border border-theme-border p-3"><TodoInlineText todo={todo} onSaved={load}/><p className="text-xs text-secondary">{(todo.received_at||todo.created_at).slice(5,10).replace('-','/')} 收到</p></article>)}{activeTeamTodos.length===0&&<p className="text-sm text-secondary">目前沒有團隊 TODO。</p>}</div></div></section>
 </div>
 {configure&&<ZoneDialog zones={zones} onClose={()=>setConfigure(false)} onSaved={load}/>}
 {promote&&<PromoteDialog todo={promote} zones={zones} projects={projects} onClose={()=>setPromote(null)} onSaved={load}/>}
 {editing&&<ItemDialog item={editing} projects={projects} editable={editable} onClose={()=>setEditing(null)} onSaved={load}/>}
 {selected&&<ProjectDetailModal project={selected.project} initialMilestoneId={selected.milestoneId} onClose={()=>setSelected(null)} onUpdate={load} onConstructionUpdated={()=>void load()} onMilestoneUpdated={()=>void load()}/>}
 </div>;
}
function Shell({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}) {return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 p-3"><div className="max-h-[90dvh] w-full max-w-lg space-y-3 overflow-y-auto rounded-xl bg-card p-4 text-primary"><header className="flex justify-between gap-2"><h2 className="font-bold">{title}</h2><button className="min-h-11 px-3" onClick={onClose} aria-label="關閉">✕</button></header>{children}</div></div>;}
function ZoneDialog({zones,onClose,onSaved}:{zones:WorkZone[];onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [count,setCount]=useState(zones.length===3?3:2),[draft,setDraft]=useState([0,1,2].map(i=>({id:zones[i]?.id,name:zones[i]?.name||''}))),[moveTo,setMoveTo]=useState(zones[0]?.id||''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 return <Shell title="設定工作區" onClose={()=>{if(!saving)onClose();}}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await workbenchAdapter.configure(draft.slice(0,count),moveTo||null);await onSaved();onClose();}catch{setError('設定失敗；請確認名稱與既有工作項目的移入區。原設定未變更。');}finally{setSaving(false);}}}><label>工作區數量<select className={field} value={count} onChange={e=>setCount(Number(e.target.value))}><option value={2}>2 區</option><option value={3}>3 區</option></select></label>{draft.slice(0,count).map((z,i)=><label key={i} className="block">工作區 {i+1}<input required className={field} value={z.name} onChange={e=>setDraft(draft.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></label>)}{zones.length>count&&<label>被移除區域的工作項目移至<select className={field} value={moveTo} onChange={e=>setMoveTo(e.target.value)}>{draft.slice(0,count).filter(z=>z.id).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}<button disabled={saving} className="min-h-11 rounded border px-4">{saving?'儲存中…':'儲存工作區'}</button></form></Shell>;
}
function PromoteDialog({todo,zones,projects,onClose,onSaved}:{todo:Todo;zones:WorkZone[];projects:Project[];onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [zone,setZone]=useState(zones[0]?.id||''),[project,setProject]=useState(''),[start,setStart]=useState(''),[due,setDue]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 return <Shell title="移入工作區" onClose={()=>{if(!saving)onClose();}}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await workbenchAdapter.promote(todo.id,zone,project||null,start||null,due||null);await onSaved();onClose();}catch{setError('移入失敗；待辦可能已收納，請重新整理確認。');}finally{setSaving(false);}}}><p className="break-words">{todo.title}</p><p className="text-xs">收到：{(todo.received_at||todo.created_at).slice(0,10)}（保留原始來源）</p><label className="block">工作區<select className={field} value={zone} onChange={e=>setZone(e.target.value)}>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><ProjectSelect projects={projects} value={project} onChange={setProject}/><label className="block">預計開始<input className={field} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="block">預計完成<input className={field} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={saving||!zone} className="min-h-11 rounded border px-4">確認移入</button></form></Shell>;
}
function ProjectSelect({projects,value,onChange}:{projects:Project[];value:string;onChange:(v:string)=>void}) {return <label className="block">案件<select className={field} value={value} onChange={e=>onChange(e.target.value)}><option value="">未指定</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;}
function ItemDialog({item,projects,editable,onClose,onSaved}:{item:WorkItem;projects:Project[];editable:boolean;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [draft,setDraft]=useState(item),[saving,setSaving]=useState(false),[error,setError]=useState('');
 return <Shell title="工作項目" onClose={()=>{if(!saving)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(!editable)return;setSaving(true);try{await workbenchAdapter.updateItem(item,{title:draft.title.trim(),content:draft.content,project_id:draft.project_id,received_at:draft.received_at,expected_start_date:draft.expected_start_date,due_date:draft.due_date,status:draft.status});await onSaved();onClose();}catch{setError('更新失敗，請重試');}finally{setSaving(false);}}}><fieldset disabled={!editable||saving} className="space-y-3"><label className="block">工作標題<input required className={field} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="block">內容<textarea className={field} value={draft.content||''} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><ProjectSelect projects={projects} value={draft.project_id||''} onChange={v=>setDraft({...draft,project_id:v||null})}/>{(['received_at','expected_start_date','due_date'] as const).map((key,i)=><label key={key} className="block">{['收到日期','預計開始','預計完成'][i]}<input type="date" required={key==='received_at'} className={field} value={draft[key]?.slice(0,10)||''} onChange={e=>setDraft({...draft,[key]:key==='received_at'?e.target.value+'T00:00:00+08:00':e.target.value||null})}/></label>)}<label className="block">狀態<select className={field} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as WorkItem['status']})}>{['待處理','進行中','已完成'].map(s=><option key={s}>{s}</option>)}</select></label><button className="min-h-11 rounded border px-4">儲存</button></fieldset>{error&&<p role="alert">{error}</p>}</form></Shell>;
}
