'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {format} from 'date-fns';
import {Check,CheckCircle2,Clock3,GripVertical,Inbox,MoreHorizontal,Settings2} from 'lucide-react';
import {useUser} from './UserContext';
import {dbAdapter} from '@/lib/db';
import {workbenchAdapter} from '@/lib/db/workbench-adapter';
import {classifyDesignTodos,sortWorkItems,workItemTimeline,type DesignTodoView,type WorkItem,type WorkZone} from '@/lib/workbench';
import type {Project,ProjectMilestone,Todo} from '@/lib/db/types';
import {TodoInlineText} from './TodoInlineText';
import {TodoContextMenu} from './TodoContextMenu';
import {TodoRow} from './TodoRow';
import {TodoQuickComposer} from './TodoQuickComposer';
import {FlexibleDateInput} from './FlexibleDateInput';
import {WorkItemProjectCombobox,type WorkItemProjectValue} from './WorkItemProjectCombobox';
import {ProjectOverviewCards} from './ProjectOverviewCards';
import {ProjectDetailModal} from './ProjectDetailModal';
import {selectActiveProjects} from '@/lib/project-selectors';
import {selectActiveTeamTodos} from '@/lib/todo-selectors';
import {formatTodoReceivedDate,presentTodoReceivedDate,taiwanDayStart} from '@/lib/todo-presentation';
import {canDeleteTodo} from '@/lib/todo-text-actions';
import {canCreateTodo,createCanonicalPrivateTodo} from '@/lib/todo-create';
import {displayWorkItemProjectLabel} from '@/lib/work-item-project';
import {presentStoredLocalDate} from '@/lib/flexible-local-date';

const field='min-h-11 w-full min-w-0 rounded-lg border border-theme-border bg-page p-2';
const todoViews:ReadonlyArray<{key:DesignTodoView;label:string}>=[{key:'pending',label:'待處理'},{key:'stored',label:'已收納'},{key:'completed',label:'已完成'}];

export function DesignWorkbench(){
 const {currentUser}=useUser();
 const [zones,setZones]=useState<WorkZone[]>([]),[items,setItems]=useState<WorkItem[]>([]),[projects,setProjects]=useState<Project[]>([]),[myIds,setMyIds]=useState<string[]>([]),[milestones,setMilestones]=useState<ProjectMilestone[]>([]),[todos,setTodos]=useState<Todo[]>([]),[teamTodos,setTeamTodos]=useState<Todo[]>([]);
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('projects'),[workTab,setWorkTab]=useState(''),[timeline,setTimeline]=useState(false),[configure,setConfigure]=useState(false),[title,setTitle]=useState(''),[saving,setSaving]=useState(false),[promote,setPromote]=useState<Todo|null>(null),[editing,setEditing]=useState<WorkItem|null>(null),[selected,setSelected]=useState<{project:Project;milestoneId:string|null}|null>(null),[todoMenu,setTodoMenu]=useState<{todo:Todo;x:number;y:number}|null>(null),[itemMenu,setItemMenu]=useState<{item:WorkItem;x:number;y:number}|null>(null),[todoView,setTodoView]=useState<DesignTodoView>('pending'),[draggingId,setDraggingId]=useState<string|null>(null),[dropZoneId,setDropZoneId]=useState<string|null>(null);
 const today=format(new Date(),'yyyy-MM-dd'),editable=canCreateTodo(currentUser);
 const load=useCallback(async()=>{if(!currentUser)return;try{const [z,i,p,ids,t,groups]=await Promise.all([workbenchAdapter.getZones(currentUser.id),workbenchAdapter.getItems(currentUser.id),dbAdapter.getProjects(),workbenchAdapter.getAssignedProjectIds(currentUser.id),dbAdapter.getPrivateTodos(),dbAdapter.getWorkGroups()]);const projectGroup=groups.find(group=>group.is_active&&group.key==='PROJECT');const [m,team]=await Promise.all([workbenchAdapter.getMilestones(ids),projectGroup?dbAdapter.getTodos(projectGroup.id):Promise.resolve([])]);setZones(z);setItems(i);setProjects(p);setMyIds(ids);setMilestones(m);setTodos(t);setTeamTodos(team);setWorkTab(old=>z.some(v=>v.id===old)?old:z[0]?.id||'');setError('');}catch{setError('無法載入設計工作台，請確認測試環境資料。');}finally{setLoading(false);}},[currentUser]);
 useEffect(()=>{void load();},[load]);
 const ordered=useMemo(()=>sortWorkItems(items,today),[items,today]),todoEntries=useMemo(()=>classifyDesignTodos(todos,items),[items,todos]),visibleTodoEntries=todoEntries.filter(entry=>entry.view===todoView),todoCounts=Object.fromEntries(todoViews.map(view=>[view.key,todoEntries.filter(entry=>entry.view===view.key).length])) as Record<DesignTodoView,number>,activeProjects=selectActiveProjects(projects),myProjects=activeProjects.filter(project=>myIds.includes(project.id)),activeTeamTodos=selectActiveTeamTodos(teamTodos);
 const runItemAction=async(action:()=>Promise<void>,failure:string)=>{if(saving)return;setSaving(true);try{await action();await load();}catch{setError(failure);}finally{setSaving(false);}};
 const moveItem=(item:WorkItem,zoneId:string)=>{if(editable&&item.work_zone_id!==zoneId)void runItemAction(()=>workbenchAdapter.moveItem(item,zoneId),'工作項目移動失敗，請重新整理後重試。');};
 const completeItem=(item:WorkItem)=>{if(editable&&item.status!=='已完成')void runItemAction(()=>workbenchAdapter.setItemStatus(item,'已完成'),'工作項目完成失敗，請重新整理後重試。');};
 const deleteItem=(item:WorkItem)=>{if(editable&&window.confirm(`確定刪除工作項目「${item.title}」？`))void runItemAction(()=>workbenchAdapter.deleteItem(item),'工作項目刪除失敗，請重新整理後重試。');};
 const deleteTodo=(todo:Todo)=>{if(canDeleteTodo(todo,currentUser)&&window.confirm(`確定刪除「${todo.title}」？`))void runItemAction(()=>todo.scope==='PRIVATE'?dbAdapter.deletePrivateTodo(todo.id):dbAdapter.deleteTodo(todo.id),'待辦刪除失敗，請重新整理後重試。');};
 if(loading)return <p className="p-5">載入設計工作台…</p>;
 return <div className="min-w-0 space-y-4 bg-page p-4 text-primary md:p-6 min-[1100px]:h-[100dvh] min-[1100px]:overflow-hidden">
  <header className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Design workspace</p><h1 className="text-2xl font-bold tracking-tight">設計工作台</h1></div><button disabled={!editable} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-theme-border bg-card px-3 text-sm font-semibold transition hover:border-accent/50 disabled:opacity-50" onClick={()=>setConfigure(true)}><Settings2 size={16}/>設定工作區</button></header>
  {error&&<p role="alert" className="rounded-lg border border-danger/30 bg-danger/10 px-3 py-2 text-sm text-danger">{error}</p>}
  <nav aria-label="設計視角頁面" className="grid grid-cols-3 gap-1 rounded-xl border border-theme-border bg-card p-1 md:hidden">{([['projects','專案'],['work','工作'],['todos','TODO']] as const).map(([key,label])=><button key={key} type="button" aria-pressed={tab===key} className="min-h-10 rounded-lg text-sm font-semibold text-secondary transition aria-pressed:bg-accent aria-pressed:text-white" onClick={()=>setTab(key)}>{label}</button>)}</nav>
  <div className="grid min-w-0 items-start gap-4 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)] min-[1100px]:h-[calc(100%-4rem)] min-[1100px]:min-h-0 min-[1100px]:grid-cols-[minmax(0,.9fr)_minmax(0,2.4fr)_minmax(0,.9fr)] min-[1100px]:items-stretch min-[1100px]:[&>section]:h-full min-[1100px]:[&>section]:overflow-y-auto">
   <section className={`${tab==='projects'?'block':'hidden'} min-w-0 rounded-2xl border border-theme-border bg-card/60 p-4 md:block`}><SectionHeading eyebrow="Projects" title="我的專案" count={myProjects.length}/><ProjectOverviewCards projects={myProjects} milestones={milestones} pending={id=>items.filter(item=>item.project_id===id&&item.status!=='已完成').length} onOpen={(project,milestoneId)=>setSelected({project,milestoneId})}/></section>
   <section className={`${tab==='work'?'block':'hidden'} min-w-0 rounded-2xl border border-theme-border bg-card/60 p-4 md:block`}>
    <div className="mb-4 hidden items-center justify-between gap-3 md:flex"><SectionHeading eyebrow="Work zones" title="工作區" count={items.filter(item=>item.status!=='已完成').length}/><div className="flex rounded-lg bg-page p-1 text-xs font-semibold"><button className="rounded-md px-3 py-1.5 text-secondary aria-pressed:bg-card aria-pressed:text-primary aria-pressed:shadow-sm" aria-pressed={!timeline} onClick={()=>setTimeline(false)}>工作區</button><button className="rounded-md px-3 py-1.5 text-secondary aria-pressed:bg-card aria-pressed:text-primary aria-pressed:shadow-sm" aria-pressed={timeline} onClick={()=>setTimeline(true)}>時間軸</button></div></div>
    {!zones.length?<div className="rounded-xl border border-dashed border-theme-border px-4 py-8 text-center text-sm text-secondary"><p>建立 2 或 3 個工作區後，即可從 TODO 收納工作。</p><button disabled={!editable} onClick={()=>setConfigure(true)} className="mt-3 min-h-10 rounded-lg border border-theme-border px-3 font-semibold text-primary">開始設定</button></div>:<><nav aria-label="工作區" className="mb-3 flex min-w-0 gap-1 overflow-x-auto rounded-xl border border-theme-border bg-page p-1 md:hidden">{zones.map(zone=><button className="min-h-10 shrink-0 rounded-lg px-3 text-sm font-semibold text-secondary aria-pressed:bg-card aria-pressed:text-primary" key={zone.id} aria-pressed={!timeline&&workTab===zone.id} onClick={()=>{setWorkTab(zone.id);setTimeline(false);}}>{zone.name}</button>)}<button className="min-h-10 shrink-0 rounded-lg px-3 text-sm font-semibold text-secondary aria-pressed:bg-card aria-pressed:text-primary" aria-pressed={timeline} onClick={()=>setTimeline(true)}>時間軸</button></nav>
    {timeline?<div className="space-y-2" aria-label="日粒度工作時間軸">{ordered.map(item=><TimelineItem key={item.id} item={item} onEdit={setEditing} onMenu={(x,y)=>setItemMenu({item,x,y})}/>)}</div>:<div className="min-w-0 overflow-x-auto pb-1"><div className="grid min-w-[600px] gap-3 md:grid-cols-2 min-[900px]:grid-cols-3 min-[1100px]:min-w-0" style={{gridTemplateColumns:`repeat(${Math.min(zones.length,3)}, minmax(180px, 1fr))`}}>{zones.map(zone=>{const zoneItems=ordered.filter(item=>item.work_zone_id===zone.id),isDropTarget=draggingId!==null&&dropZoneId===zone.id;return <section key={zone.id} className={`${workTab===zone.id?'block':'hidden'} min-w-0 rounded-xl border p-2.5 transition md:block ${isDropTarget?'border-accent/70 bg-accent/5 ring-2 ring-accent/20':'border-theme-border/70 bg-page/45'}`} onDragOver={event=>{if(!editable)return;event.preventDefault();event.dataTransfer.dropEffect='move';setDropZoneId(zone.id);}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDropZoneId(null);}} onDrop={event=>{event.preventDefault();const item=items.find(row=>row.id===(draggingId||event.dataTransfer.getData('text/plain')));setDraggingId(null);setDropZoneId(null);if(item)moveItem(item,zone.id);}}><header className="mb-2.5 flex items-center justify-between gap-2 border-b border-theme-border/60 px-1 pb-2"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-secondary">Work zone</p><h2 className="truncate text-base font-bold">{zone.name}</h2></div><span className="rounded-full bg-card px-2 py-.5 text-[11px] font-semibold text-secondary">{zoneItems.length}</span></header><div className="space-y-2">{zoneItems.map(item=><WorkItemCard key={item.id} item={item} projects={projects} today={today} editable={editable} dragging={draggingId===item.id} onEdit={()=>setEditing(item)} onMenu={(x,y)=>setItemMenu({item,x,y})} onDragStart={event=>{setDraggingId(item.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',item.id);}} onDragEnd={()=>{setDraggingId(null);setDropZoneId(null);}}/>)}{!zoneItems.length&&<div className="rounded-lg border border-dashed border-theme-border/70 px-3 py-6 text-center text-xs text-secondary/80"><Inbox className="mx-auto mb-2 opacity-50" size={18}/>從 TODO 移入工作項目</div>}</div></section>;})}</div></div>}</>}
   </section>
   <section className={`${tab==='todos'?'block':'hidden'} min-w-0 space-y-5 rounded-2xl border border-theme-border bg-card/60 p-4 md:col-span-2 md:block min-[1100px]:col-span-1`}><div><SectionHeading eyebrow="Inbox" title="我的 TODO" count={todoCounts[todoView]}/><TodoQuickComposer value={title} onChange={setTitle} onSubmit={async event=>{event.preventDefault();if(!title.trim()||!editable||saving)return;setSaving(true);try{await createCanonicalPrivateTodo(title,currentUser);setTitle('');await load();}catch{setError('新增待辦失敗');}finally{setSaving(false);}}} placeholder="新增私人記事…" disabled={!editable} isSaving={saving}/><nav aria-label="我的 TODO 狀態" className="mb-3 grid grid-cols-3 rounded-lg bg-page p-1">{todoViews.map(view=><button key={view.key} type="button" aria-pressed={todoView===view.key} onClick={()=>setTodoView(view.key)} className="min-h-9 rounded-md px-1 text-xs font-semibold text-secondary transition aria-pressed:bg-card aria-pressed:text-primary aria-pressed:shadow-sm">{view.label}<span className="ml-1 text-[10px] opacity-70">{todoCounts[view.key]}</span></button>)}</nav><div className="space-y-2">{visibleTodoEntries.map(({todo,item,view})=><DesignTodoCard key={todo.id} todo={todo} item={item} view={view} zones={zones} actor={currentUser} editable={editable} saving={saving} onSaved={load} onPromote={()=>setPromote(todo)} onComplete={()=>void runItemAction(()=>dbAdapter.updatePrivateTodo(todo.id,{status:'已完成'}).then(()=>undefined),'待辦更新失敗')} onOpenItem={()=>{if(item)setEditing(item);}} onMenu={(x,y)=>setTodoMenu({todo,x,y})}/>)}{!visibleTodoEntries.length&&<p className="rounded-lg border border-dashed border-theme-border/70 px-3 py-5 text-center text-xs text-secondary">此狀態目前沒有 TODO</p>}</div></div><div><h2 className="mb-3 text-sm font-bold">團隊 TODO <span className="ml-1 text-xs font-normal text-secondary">{activeTeamTodos.length}</span></h2><div className="space-y-2">{activeTeamTodos.map(todo=><TodoRow key={todo.id} todo={todo} className="rounded-lg border border-theme-border/70 bg-page/45 p-3" menuDisabled={!canDeleteTodo(todo,currentUser)} onOpenMenu={point=>setTodoMenu({todo,...point})} title={<TodoInlineText todo={todo} onSaved={load}/>} secondaryClassName="" secondary={<TodoReceivedDate todo={todo} editable={editable} onSaved={load}/>}/>)}{!activeTeamTodos.length&&<p className="text-xs text-secondary">目前沒有團隊 TODO。</p>}</div></div></section>
  </div>
  {configure&&<ZoneDialog zones={zones} onClose={()=>setConfigure(false)} onSaved={load}/>} {promote&&<PromoteDialog todo={promote} zones={zones} projects={projects} onClose={()=>setPromote(null)} onSaved={load}/>} {editing&&<ItemDialog item={editing} zones={zones} projects={projects} editable={editable} onClose={()=>setEditing(null)} onSaved={load}/>}<TodoContextMenu point={todoMenu?{x:todoMenu.x,y:todoMenu.y}:null} onClose={()=>setTodoMenu(null)} actions={todoMenu?[{label:'刪除待辦',tone:'danger',onSelect:()=>deleteTodo(todoMenu.todo)}]:[]}/><TodoContextMenu label="工作項目操作" point={itemMenu?{x:itemMenu.x,y:itemMenu.y}:null} onClose={()=>setItemMenu(null)} actions={itemMenu?[{label:'編輯',tone:'accent',onSelect:()=>setEditing(itemMenu.item)},{label:'完成',onSelect:()=>completeItem(itemMenu.item),disabled:itemMenu.item.status==='已完成'},{label:'刪除',tone:'danger',onSelect:()=>deleteItem(itemMenu.item),disabled:!editable}]:[]}/>{selected&&<ProjectDetailModal project={selected.project} initialMilestoneId={selected.milestoneId} onClose={()=>setSelected(null)} onUpdate={load} onConstructionUpdated={()=>void load()} onMilestoneUpdated={()=>void load()}/>}
 </div>;
}

function SectionHeading({eyebrow,title,count}:{eyebrow:string;title:string;count:number}){return <div className="mb-3 min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-accent">{eyebrow}</p><div className="flex items-center gap-2"><h2 className="truncate text-lg font-bold tracking-tight">{title}</h2><span className="rounded-full bg-page px-2 py-.5 text-[11px] font-semibold text-secondary">{count}</span></div></div>;}
function WorkItemCard({item,projects,today,editable,dragging,onEdit,onMenu,onDragStart,onDragEnd}:{item:WorkItem;projects:Project[];today:string;editable:boolean;dragging:boolean;onEdit:()=>void;onMenu:(x:number,y:number)=>void;onDragStart:(event:React.DragEvent<HTMLElement>)=>void;onDragEnd:()=>void}){const received=presentStoredLocalDate(item.received_at),overdue=item.status!=='已完成'&&item.due_date&&item.due_date<today;return <article draggable={editable} onDragStart={onDragStart} onDragEnd={onDragEnd} onContextMenu={event=>{event.preventDefault();event.stopPropagation();onMenu(event.clientX,event.clientY);}} className={`group rounded-xl border border-theme-border/70 bg-card p-3 shadow-sm transition hover:border-theme-border hover:shadow-md ${dragging?'opacity-45':''}`}><div className="flex items-start gap-2"><GripVertical size={15} className="mt-.5 hidden shrink-0 cursor-grab text-secondary/45 group-hover:text-secondary md:block"/><div className="min-w-0 flex-1"><p className="break-words text-[11px] font-medium leading-4 text-secondary">{displayWorkItemProjectLabel(item,projects)||'未指定案件'}</p><button type="button" onClick={onEdit} className="mt-1 block min-h-9 w-full break-words text-left text-sm font-bold leading-5">{item.title}</button></div><MenuButton label={`工作項目操作：${item.title}`} onMenu={onMenu}/></div><dl className="mt-2 grid grid-cols-2 gap-x-2 gap-y-1 border-t border-theme-border/50 pt-2 text-[11px] leading-4 text-secondary"><div className={received.invalid?'text-danger':''}>收到 {received.label}</div><div><StatusBadge status={item.status}/></div><div>開始 {item.expected_start_date||'—'}</div><div className={overdue?'text-danger':''}>完成 {item.due_date||'—'}{overdue?' · 逾期':''}</div></dl></article>;}
function MenuButton({label,onMenu}:{label:string;onMenu:(x:number,y:number)=>void}){return <button type="button" aria-label={label} onClick={event=>{event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();onMenu(rect.right,rect.bottom);}} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-secondary transition hover:bg-page hover:text-primary md:opacity-0 md:group-hover:opacity-100 md:focus:opacity-100"><MoreHorizontal size={17}/></button>;}
function TimelineItem({item,onEdit,onMenu}:{item:WorkItem;onEdit:(item:WorkItem)=>void;onMenu:(x:number,y:number)=>void}){return <article onContextMenu={event=>{event.preventDefault();onMenu(event.clientX,event.clientY);}} className="group rounded-xl border border-theme-border/70 bg-page/45 p-3"><div className="flex items-start justify-between gap-2"><button className="min-h-9 break-words text-left text-sm font-bold" onClick={()=>onEdit(item)}>{item.title}</button><MenuButton label={`工作項目操作：${item.title}`} onMenu={onMenu}/></div><ol className="mt-2 flex flex-wrap gap-3 text-[11px] text-secondary">{workItemTimeline(item).map(point=><li key={point.label}><span className="block font-semibold text-primary/70">{point.label}</span>{point.date}</li>)}</ol></article>;}
function StatusBadge({status}:{status:WorkItem['status']}){const style=status==='已完成'?'bg-success/10 text-success':status==='進行中'?'bg-accent/10 text-accent':'bg-page text-secondary';return <span className={`inline-flex rounded-full px-1.5 py-.5 text-[10px] font-semibold ${style}`}>{status}</span>;}
function DesignTodoCard({todo,item,view,zones,actor,editable,saving,onSaved,onPromote,onComplete,onOpenItem,onMenu}:{todo:Todo;item:WorkItem|null;view:DesignTodoView;zones:WorkZone[];actor:ReturnType<typeof useUser>['currentUser'];editable:boolean;saving:boolean;onSaved:()=>Promise<void>;onPromote:()=>void;onComplete:()=>void;onOpenItem:()=>void;onMenu:(x:number,y:number)=>void}){const zone=item?zones.find(row=>row.id===item.work_zone_id):null;if(view!=='pending')return <article className="rounded-lg border border-theme-border/60 bg-page/40 p-3"><div className="flex items-start gap-2"><span className={`mt-.5 ${view==='completed'?'text-success':'text-accent'}`}>{view==='completed'?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</span><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{todo.title}</p><p className="mt-1 text-[11px] text-secondary">{view==='completed'?'已完成':'已收納'} · {zone?.name||(item?'工作區已停用':'原工作項目已刪除')}</p>{item&&<button type="button" onClick={onOpenItem} className="mt-1 text-left text-[11px] font-semibold text-accent hover:underline">對應工作項目：{item.title}</button>}</div></div></article>;return <TodoRow todo={todo} className="rounded-lg border border-theme-border/70 bg-page/45 p-3" menuDisabled={!canDeleteTodo(todo,actor)} onOpenMenu={point=>onMenu(point.x,point.y)} title={<TodoInlineText todo={todo} onSaved={onSaved}/>} secondaryClassName="" secondary={<><TodoReceivedDate todo={todo} editable={editable} onSaved={onSaved}/><div className="flex flex-wrap items-center gap-2"><button disabled={!editable||!zones.length} onClick={onPromote} className="min-h-9 text-xs font-semibold text-accent">移入工作區</button><button disabled={!editable||saving} className="inline-flex min-h-9 items-center gap-1 text-xs font-semibold text-secondary hover:text-accent" onClick={onComplete}><Check size={14}/>完成</button><MenuButton label={`待辦操作：${todo.title}`} onMenu={onMenu}/></div></>}/>;}
function TodoReceivedDate({todo,editable,onSaved}:{todo:Todo;editable:boolean;onSaved:()=>Promise<void>}){const [editing,setEditing]=useState(false),[date,setDate]=useState((todo.received_at??todo.created_at).slice(0,10)),[saving,setSaving]=useState(false);if(!editing)return <button type="button" disabled={!editable} className="mt-1 min-h-9 text-left text-xs text-secondary underline-offset-2 hover:underline disabled:no-underline" onClick={()=>setEditing(true)}>{formatTodoReceivedDate(todo.received_at||todo.created_at)}</button>;return <div className="mt-1 text-xs"><FlexibleDateInput label="修改收到日期" required value={date} disabled={saving} onChange={async next=>{if(!next)return;setDate(next);setSaving(true);try{const update={received_at:taiwanDayStart(next)};if(todo.scope==='PRIVATE')await dbAdapter.updatePrivateTodo(todo.id,update);else await dbAdapter.updateTodo(todo.id,update);await onSaved();setEditing(false);}finally{setSaving(false);}}}/></div>;}
function Shell({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 p-3"><div className="max-h-[90dvh] w-full max-w-lg space-y-3 overflow-y-auto rounded-xl bg-card p-4 text-primary shadow-2xl"><header className="flex justify-between gap-2"><h2 className="font-bold">{title}</h2><button className="min-h-11 px-3" onClick={onClose} aria-label="關閉">✕</button></header>{children}</div></div>;}
function ZoneDialog({zones,onClose,onSaved}:{zones:WorkZone[];onClose:()=>void;onSaved:()=>Promise<void>}){const [count,setCount]=useState(zones.length===3?3:2),[draft,setDraft]=useState([0,1,2].map(i=>({id:zones[i]?.id,name:zones[i]?.name||''}))),[moveTo,setMoveTo]=useState(zones[0]?.id||''),[error,setError]=useState(''),[saving,setSaving]=useState(false);return <Shell title="設定工作區" onClose={()=>{if(!saving)onClose();}}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await workbenchAdapter.configure(draft.slice(0,count),moveTo||null);await onSaved();onClose();}catch{setError('設定失敗；請確認名稱與既有工作項目的移入區。原設定未變更。');}finally{setSaving(false);}}}><label>工作區數量<select className={field} value={count} onChange={e=>setCount(Number(e.target.value))}><option value={2}>2 區</option><option value={3}>3 區</option></select></label>{draft.slice(0,count).map((z,i)=><label key={i} className="block">工作區 {i+1}<input required className={field} value={z.name} onChange={e=>setDraft(draft.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></label>)}{zones.length>count&&<label>被移除區域的工作項目移至<select className={field} value={moveTo} onChange={e=>setMoveTo(e.target.value)}>{draft.slice(0,count).filter(z=>z.id).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}<button disabled={saving} className="min-h-11 rounded border px-4">{saving?'儲存中…':'儲存工作區'}</button></form></Shell>;}
function PromoteDialog({todo,zones,projects,onClose,onSaved}:{todo:Todo;zones:WorkZone[];projects:Project[];onClose:()=>void;onSaved:()=>Promise<void>}){const [zone,setZone]=useState(zones[0]?.id||''),[project,setProject]=useState<WorkItemProjectValue>({projectId:null,projectLabel:null}),[start,setStart]=useState<string|null>(null),[due,setDue]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('');const received=presentTodoReceivedDate(todo.received_at??todo.created_at);return <Shell title="移入工作區" onClose={()=>{if(!saving)onClose();}}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await workbenchAdapter.promote(todo.id,zone,project.projectId,project.projectLabel,start,due);await onSaved();onClose();}catch{setError('移入失敗；待辦可能已收納，或測試環境 schema 尚未更新。');}finally{setSaving(false);}}}><p className="break-words font-semibold">{todo.title}</p><p className={`text-xs ${received.invalid?'text-danger':'text-secondary'}`}>收到：{received.label}{received.invalid?'（保留原始值，未自動改寫）':'（保留原始來源）'}</p><label className="block">工作區<select className={field} value={zone} onChange={e=>setZone(e.target.value)}>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="block">案件<WorkItemProjectCombobox projects={selectActiveProjects(projects)} value={project} onChange={setProject}/></label><div><span className="block">預計開始</span><FlexibleDateInput label="預計開始" value={start} onChange={setStart}/></div><div><span className="block">預計完成</span><FlexibleDateInput label="預計完成" value={due} onChange={setDue}/></div>{error&&<p role="alert">{error}</p>}<button disabled={saving||!zone} className="min-h-11 rounded border px-4">確認移入</button></form></Shell>;}
function ItemDialog({item,zones,projects,editable,onClose,onSaved}:{item:WorkItem;zones:WorkZone[];projects:Project[];editable:boolean;onClose:()=>void;onSaved:()=>Promise<void>}){const [draft,setDraft]=useState(item),[saving,setSaving]=useState(false),[error,setError]=useState('');return <Shell title="工作項目" onClose={()=>{if(!saving)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(!editable)return;setSaving(true);try{await workbenchAdapter.updateItem(item,{title:draft.title.trim(),content:draft.content,project_id:draft.project_id,project_label:draft.project_label,received_at:draft.received_at,expected_start_date:draft.expected_start_date,due_date:draft.due_date,status:draft.status});if(draft.work_zone_id!==item.work_zone_id)await workbenchAdapter.moveItem(item,draft.work_zone_id);await onSaved();onClose();}catch{setError('更新失敗，請重試');}finally{setSaving(false);}}}><fieldset disabled={!editable||saving} className="space-y-3"><label className="block">工作標題<input required className={field} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="block">內容<textarea className={field} value={draft.content||''} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label className="block">工作區<select className={field} value={draft.work_zone_id} onChange={e=>setDraft({...draft,work_zone_id:e.target.value})}>{zones.map(zone=><option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label className="block">案件<WorkItemProjectCombobox projects={selectActiveProjects(projects)} value={{projectId:draft.project_id,projectLabel:draft.project_label}} onChange={value=>setDraft({...draft,project_id:value.projectId,project_label:value.projectLabel})}/></label><div><span className="block">收到日期</span><FlexibleDateInput label="收到日期" required value={draft.received_at} onChange={value=>{if(value)setDraft({...draft,received_at:`${value}T00:00:00+08:00`});}}/></div><div><span className="block">預計開始</span><FlexibleDateInput label="預計開始" value={draft.expected_start_date} onChange={value=>setDraft({...draft,expected_start_date:value})}/></div><div><span className="block">預計完成</span><FlexibleDateInput label="預計完成" value={draft.due_date} onChange={value=>setDraft({...draft,due_date:value})}/></div><label className="block">狀態<select className={field} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as WorkItem['status']})}>{['待處理','進行中','已完成'].map(s=><option key={s}>{s}</option>)}</select></label><button className="min-h-11 rounded border px-4">儲存</button></fieldset>{error&&<p role="alert">{error}</p>}</form></Shell>;}
