'use client';
import {useState} from 'react';
import {supabase} from '@/lib/db/supabaseClient';
interface Preview {matched:number;added:number;archived:number;custom:number;token:string}
export function WorkflowRebuild({projectId,onRebuilt}:{projectId:string;onRebuilt:()=>Promise<void>}) {
 const [preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function inspect(){setBusy(true);setError('');try{const {data,error}=await supabase.rpc('preview_project_workflow_rebuild',{p_project_id:projectId});if(error)throw error;setPreview(data as Preview);}catch{setError('無法取得重建預覽，請確認權限與 candidate migration。');}finally{setBusy(false);}}
 async function rebuild(){if(!preview||busy)return;setBusy(true);setError('');try{const {error}=await supabase.rpc('rebuild_project_workflow',{p_project_id:projectId,p_preview_token:preview.token});if(error)throw error;setPreview(null);await onRebuilt();}catch{setError('重建未完成；資料可能已更新，請關閉後重新取得預覽。');setPreview(null);}finally{setBusy(false);}}
 return <><button type="button" disabled={busy} onClick={()=>void inspect()} className="min-h-11 rounded border border-theme-border px-3 text-sm">重建流程框架</button>{error&&<p role="alert" className="w-full break-words text-sm text-danger">{error}</p>}{preview&&<div role="dialog" aria-modal="true" aria-labelledby="rebuild-title" className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 p-3"><div className="max-h-[90dvh] w-full max-w-lg space-y-4 overflow-y-auto rounded-xl bg-card p-5 text-primary"><h2 id="rebuild-title" className="font-bold">重建流程框架 · 預覽</h2><ul className="space-y-2"><li>將更新框架的既有 milestone：{preview.matched}</li><li>將新增 template milestone：{preview.added}</li><li>模板已移除，轉為封存：{preview.archived}</li><li>保留自訂 milestone：{preview.custom}</li></ul><p className="text-sm text-secondary">依 template step ID 精確配對。保留狀態、預計／實際日期、備註與自訂項目。封存項目仍可查閱歷史。資料變更後必須重新預覽。</p><div className="flex justify-end gap-3"><button disabled={busy} onClick={()=>setPreview(null)} className="min-h-11 rounded border px-3">取消</button><button disabled={busy} onClick={()=>void rebuild()} className="min-h-11 rounded bg-accent px-3">確認重建框架</button></div></div></div>}</>;
}
